### ISSUE TITLE
Add in coassembly feature.

### ISSUE THREAD

**Issue by rroutsong** [OpenOmics/metamorph#6]
metamorph pipeline is in the process of being assembled in a strictly per-sample method. this pipeline also needs to be able to run in a cohort fashion. This invovles read concatination of the entire cohort of samples and follow through with the pipeline in the same manner as the per-sample pipeline. Therefore I purpose to develope this workflow as such:

```[tasklist]
### Tasks
- [x] Finish the pipeline in prototypical fashion that is able to execute the per-sample workflow end to end.
- [x] Develop sample pairing and disrupted read collapsing feature of the per-sample workflow
- [ ] Add in cohort functionality by assembling snakemake logic to accept cli flag and merge all collapsed reads before assembly, etc.
```

**Comment by rroutsong** [comment]
<img width="670" alt="Screenshot 2023-09-16 at 12 53 55 PM" src="https://github.com/OpenOmics/metamorph/assets/124383/e8ffccee-72ef-45b3-8b65-bb483ab4fb23">

**Comment by rroutsong** [comment]
closing because of the disk space issues related to coassembly
